### ISSUE TITLE
pipelines: add multi-stage support | `feature` `ux`

### ISSUE THREAD

**Issue by e2corporation** [merico-dev/lake#1007]
## Config-UI / Pipelines / Multi-Stage Support

In order to properly support multiple stages, the Pipeline UX flow has to be enhanced. This is a future feature ticket to be revisited once the first iteration of **Pipelines** (#962) is completed. This is a future feature to be discussed further and added to iteration planning.
[`UPDATE REQUIRED...`]

- [ ] Create draft Multi-Stage Design Mockup Proposal(s)
- [ ] Alter **Create Pipeline** UX Workflow to allow STAGES
  - Each Stage should maintain it's own Task Configuration
  - Consider placing a hard-limit on max stages, eg `5` Stages Max
  - [`...`]
- [ ] Alter **Pipeline Activity** UX
  - Enhance Stage Visualization
  - Group Tasks by Stage
  - [`...`]
  
  
#### Related Tickets
- #962
- #963 
- #964 
- #965

**Comment by klesh** [comment]
This is done AFAIK, feel free to re-open if I mistaken
