### ISSUE TITLE
Add roadmap, metric summary to READMEs and simplify the main README

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#1261]
## Documentation Scope
- main README
- a README for roadmap
- a README for all metrics

## Describe the Change

- [ ] Add roadmap to main README so that the community knows.
- [ ] Add metric summary entry to the main README
- [ ] simplify the main README by only keeping the titles, move the detailed info to sub-READMEs

**Comment by Startrekzky** [comment]
Merged.
