### ISSUE TITLE
v0.10 testing plan

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#1500]
## Description
It has been a long month since we started v0.10 refactor, along with many features/bugfixes. We ought to go through the testing/verfication process more thoroughly.

### Plan of attack

Dividing test tasks into two categories, each of them has different workflow:

1. plugin test
2. framework test

### Plugin test (except for `dbt` plugin`)

Create an issue(**specific testing issue**) for particular plugin you are working on, assign it to youself, and put a link in this issue.

#### Plugin Assignement:

- ae https://github.com/merico-dev/lake/issues/1591
- feishu  #1579 
- gitextractor https://github.com/merico-dev/lake/issues/1569
- github https://github.com/merico-dev/lake/issues/1504
- gitlab: https://github.com/merico-dev/lake/issues/1501
- jenkins https://github.com/merico-dev/lake/issues/1583
- jira:https://github.com/merico-dev/lake/issues/1509
- refdiff:https://github.com/merico-dev/lake/issues/1631

For each of every plugin, the following operations are required, and must be presented as **Checklist** in **specific testing issue**:

- [ ] Main readme and plugin readme are up to date
- [ ] Trigger plugin with only required options and record following information
  - [ ] Which board/repo you collected against?
  - [ ] How many subtasks are executed by default?
  - [ ] How long did it take to finish the whole process?
  - [ ] How many records did each subtasks generated, and how many shoud it be according to data source if avaiable?
  - [ ] What do you think of the plugin status? Is good enough for you? performance-wise, data-wise.
- [ ] Trigger plugin with `tasks` field for those `EnabledByDefault` set to `false`
  - [ ] Which board/repo you collected against?
  - [ ] What subtasks did you specify?
  - [ ] How long did it take to finish the whole process?
  - [ ] How many records did each subtasks generated, and how many shoud it be according to data source if avaiable?
  - [ ] What do you think of the plugin status? Is good enough for you? performance-wise, data-wise.
- [ ] Screen-shots or test-snipet that can show plugin works properly.
- [ ] Create issue for each and every bug you found during the whole process, and add link to **plugin testing issue**
- [ ] Fill out table on #1500 to what domain layer entities could a plugin provide, `default` means it was produced by default, `optional` means it was produced only when specified by using `tasks` field (aka. `EnabledByDefault=false`

| Domain Layer Entity  | ae   | gitextractor | github   | gitlab | jenkins | jira | refdiff |
| -------------------- | ---- | ------ | -------- | ------ | ------- | ---- | ------- |
| commits               | update commits|     default   | optional |   default     |         |      |         |
| commit_parents        |      |   default     |    |        |         |      |         |
| commit_files        |      |    default    | |        |         |      |         |
| pull_requests         |      |        | default  | default |         |      |         |
| pull_request_commits  |      |        | default  | default |         |      |         |
| pull_request_comments |      |        | default  | default |         |      |         |
| pull_request_labels   |      |        | default  |        |         |      |         |
| refs                  |      |   default     |          |        |         |      |         |
| refs_commits_diffs    |      |        |          |        |         |      |    default     |
| refs_issues_diffs    |      |        |          |        |         |      |    default     |
| ref_pr_cherry_picks   |      |        |          |        |         |      |   default      |
| repos                 |      |        | default  | default |         |      |         |
| repo_commits          |      |    default    | default  |        |         |      |         |
| board_repos           |      |        |          |        |         |      |         |
| issue_commits         |      |        |          |        |         |      |         |
| issue_repo_commits    |      |        |          |        |         |      |         |
| pull_request_issues   |      |        |          |        |         |      |         |
| refs_issues_diffs     |      |        |          |        |         |      |         |
| builds                |      |        |          |        |         |      |         |
| jobs                  |      |        |          |        |         |      |         |
| boards                |      |        | default  |        |         |      |         |
| board_issues          |      |        | default  |        |         |      |         |
| issue_changelogs            |      |        |          |        |         |      |         |
| issues               |      |        | default  |        |         |      |         |
| issue_comments        |      |        |          |        |         |      |         |
| issue_labels          |      |        | default  |        |         |      |         |
| sprints               |      |        |          |        |         |      |         |
| issue_worklogs              |      |        |          |        |         |      |         |
| users               |      |        |   default       |        |         |      |         |

### Framework task (including dbt plugin)

Create an issue for particular feature/plugin you are working on, assign it to youself, and put a link in this issue.

#### Feature/Plugin Assignement:

- temporal @mindlesscloud 
- dbt  https://github.com/merico-dev/lake/issues/1505
- db migration @warren830 
- pipeline blueprint @klesh #1595
- config-ui @yumeng

For each of every feature/plugin, the following operations are required, and must be presented as **Checklist** in **specific testing issue**:

- [ ] Write `Plan of attack` for each feature/plugin (short description of what a plugin for, how would you testing)
- [ ] Link `Plan of attack` to this issue
- [ ] Carry out plan and record result

**Comment by abeizn** [comment]
v0.10.0 dbt test #1505

**Comment by yumengwang03** [comment]
v0.10.0 Config UI Test https://github.com/merico-dev/lake/issues/1599

**Comment by klesh** [comment]
@Startrekzky Please convert the table above to documentation site and close this issue

**Comment by Startrekzky** [comment]
> @Startrekzky Please convert the table above to documentation site and close this issue

The table has been moved to [DevLake website](https://www.devlake.io/docs/DataModels/DataSources).
