### ISSUE TITLE
Pre-release testing notes for v0.10.0-beta1

### ISSUE THREAD

**Issue by hezyin** [merico-dev/lake#1648]
This issue documents what closed issues I verified prior to releasing the beta. I compiled this list of issues from PRs merged in the past 2 days: 

- [x] [1661 Git Extractor Repo ID field's prompt needs adjustment](https://github.com/merico-dev/lake/issues/1661)
- [x] [1653 remove multiple board_id / project_id from config-ui](https://github.com/merico-dev/lake/pull/1653): only partially resolved, filed another issue: https://github.com/merico-dev/lake/issues/1657
- [x] [1610 NextRunDate is incorrect](https://github.com/merico-dev/lake/issues/1610): see below for screenshots
- [x] [1644 The Repository ID field of Git Extractor on pipeline creation page has overflow](https://github.com/merico-dev/lake/issues/1644)
- [x] [1646 Use cron-parser for expression parsing](https://github.com/merico-dev/lake/issues/1646): this is the same issue as 1610
- [x] [1590 Hide "Triggers" in the side nav bar](https://github.com/merico-dev/lake/issues/1590)
- [x] [1613 Save connection failed for GitHub](https://github.com/merico-dev/lake/issues/1613)
- [x] [1637 `PUT /plugins/jira/sources/:id` returns `basicAuthEncoded` as encrypted](https://github.com/merico-dev/lake/issues/1637): see below for screenshot
- [x] [1616 Config UI - Create Blueprint naming confusion](https://github.com/merico-dev/lake/issues/1616)
- [x] [1626 Config UI - Auto-open Blueprint Dialog when pipeline automation is toggled ON](https://github.com/merico-dev/lake/issues/1626)
- [x] [1632 pipeline duration is incorrect](https://github.com/merico-dev/lake/issues/1632)
- [x] (1620 Jenkins data inconsistent between different collection runs](https://github.com/merico-dev/lake/issues/1620)
- [x] (1490 WaitAsync not working] (https://github.com/merico-dev/lake/issues/1490): same issue as 1620
- [x] (1621 Config UI - "Create Blueprint" dialog doesn't disappear after Blueprint is saved](https://github.com/merico-dev/lake/issues/1621) 
- [x] [1465 Allow users to select repo from a dropdown list for Git Extractor](https://github.com/merico-dev/lake/issues/1465): found a typo while verifying this issue
- [x] [1607 Names of pipelines triggered by Blueprint don't seem right](https://github.com/merico-dev/lake/issues/1607)

Besides the issues above, the following plugins are also tested:

- [x] GitLab: collected the data of project 11624398 in our GitLab (took 11 mins)
- [x] Jira: collected the data of board 76 of our Jira instance （took 1min)
- [x] GitHub: collected lake's own data (took 4 mins)
- [x] Git Extractor: collected lake's own data after collecting lake with GitHub (took 1 min)
- [x] Jenkins: collected our own Jenkins data twice (each took 1 min), both times give the exact same amount of jobs and builds

## New Issues Found

- [x] https://github.com/merico-dev/lake/issues/1649

## Screenshots & Notes

- [1610 NextRunDate is incorrect](https://github.com/merico-dev/lake/issues/1610)

I'm in PDT (GMT-7), so GMT midnight is my 5 pm. 

<img width="498" alt="Screen Shot 2022-04-17 at 4 22 00 PM" src="https://user-images.githubusercontent.com/2908155/163735882-6765c1eb-1629-49bb-ba23-846f4925fb7c.png">
<img width="503" alt="Screen Shot 2022-04-17 at 4 21 55 PM" src="https://user-images.githubusercontent.com/2908155/163735885-a932b014-f386-4c78-b234-a69e63e13ad1.png">
<img width="499" alt="Screen Shot 2022-04-17 at 4 21 03 PM" src="https://user-images.githubusercontent.com/2908155/163735888-b85c593a-b17a-4ac8-9423-c2925e97e7e1.png">

- [1637 `PUT /plugins/jira/sources/:id` returns `basicAuthEncoded` as encrypted](https://github.com/merico-dev/lake/issues/1637)

<img width="2079" alt="Screen Shot 2022-04-17 at 4 52 03 PM" src="https://user-images.githubusercontent.com/2908155/163736802-3b5e397c-bd37-4842-9372-e386d698a55a.png">

- [1644 The Repository ID field of Git Extractor on pipeline creation page has overflow](https://github.com/merico-dev/lake/issues/1644)
<img width="971" alt="Screen Shot 2022-04-17 at 11 16 02 PM" src="https://user-images.githubusercontent.com/2908155/163764119-2af63f0f-bb56-40b4-88d5-9dbc9432029b.png">

- [1632 pipeline duration is incorrect](https://github.com/merico-dev/lake/issues/1632)

<img width="1366" alt="Screen Shot 2022-04-17 at 11 39 07 PM" src="https://user-images.githubusercontent.com/2908155/163766654-5d36f273-c60e-4186-ade1-ec2829cc2799.png">
<img width="1276" alt="Screen Shot 2022-04-17 at 11 55 47 PM" src="https://user-images.githubusercontent.com/2908155/163768585-30f0db09-174b-4776-9b68-d4a544afd449.png">

- [1607 Names of pipelines triggered by Blueprint don't seem right](https://github.com/merico-dev/lake/issues/1607)

I created two blueprints with different names and they created pipelines with different names.
<img width="2283" alt="Screen Shot 2022-04-18 at 1 00 55 AM" src="https://user-images.githubusercontent.com/2908155/163777072-84d7d971-9261-44d9-8e00-dc56429b500e.png">
<img width="2280" alt="Screen Shot 2022-04-18 at 1 00 49 AM" src="https://user-images.githubusercontent.com/2908155/163777085-52d106a4-8f13-437b-a84d-749ddea13299.png">
