### ISSUE TITLE
Golang - Lake v2 Roadmap

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#196]
These are issues that we want to work on later. This is where we should store all notes on work we plan to do after the MVP.

## Notes

- The date of starting v2 is not set yet.
- This plan can reference closed issues that we can re-open as needed when the v2 starts
- When v2 starts, all issues get labelled with "Help Wanted" and "v2"

## Potential Issues:

#183 - Switch to yarn instead of npm
https://github.com/merico-dev/lake/issues/221 - Add common business terms to grafana homepage

- [ ] Improve log: see if we can display percentage for each step?
- [ ] Merge emails for # of contributors
- [ ] Incrementally update commits (if doable)?
- [ ] Always delete all commits before collection because of force push?
- [ ] Handle scaling up of docker containers and workers. IE: Stop using concurrently.
- [ ] Progress bar for collection and enrichment @Klesh Wong 
- [ ] Can we implement this via Grafana?
- [ ] API limit
- [ ] Video demo
- [ ] Get whether a commit is merge commit from Gitlab instead of guessing with commit message
- [ ] Configuration
- [ ] Add a switch for turning on/off individual plugins
- [ ] Make what needs to be edited more obvious for users in config/docker.sample.js and config/local.sample.js
- [ ] Seed our postgres database with sample data

**Comment by hezyin** [comment]
Done
