### ISSUE TITLE
Golang - Lake v1 Roadmap

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#197]
** This is the current phase of implementation as of Aug 12, 2021 **

These are issues that we want to work on now. This is where we should store all notes on work we plan to do after the Javascript MVP.

## Notes

- The date to complete this is 9/14.
- All work for this milestone is merged to the branch `ts-main`

## Proposed Issues

#139 - Differences in typescript app vs javascript app

- [ ] Make all features from the main branch work on ts-main

## Jira

- [ ] Pull in jira issues https://github.com/merico-dev/lake/pull/11 https://github.com/merico-dev/lake/pull/16 https://github.com/merico-dev/lake/pull/13
- [ ] Lead time on Jira issues https://github.com/merico-dev/lake/pull/15 https://github.com/merico-dev/lake/pull/77
- [ ] Collect jira changelogs (@UltimateBeaver I think we may no longer need changelogs. Can you confirm?) https://github.com/merico-dev/lake/pull/18
- [ ] Enrich with lead time - https://github.com/merico-dev/lake/pull/46
- [ ] Get all below metrics working in granafa 

Metric Name | Description
:------------ | :-------------
Requirement Count	| Number of issues with type "Requirement"
Requirement Lead Time	| Lead time of issues with type "Requirement"
Requirement Delivery Rate |	Ratio of delivered requirements to all requirements
Bug Count	| Number of issues with type "Bug"<br><i>bugs are found during testing</i>
Bug Age	| Lead time of issues with type "Bug"<br><i>both new and deleted lines count</i>
Bugs Count per 1k Lines of Code |	Amount of bugs per 1000 lines of code
Incident Count | Number of issues with type "Incident"<br><i>incidents are found when running in production</i>
Incident Age | Lead time of issues with type "Incident"
Incident Count per 1k Lines of Code | Amount of incidents per 1000 lines of code

## Gitlab

- [ ] Collection
https://github.com/merico-dev/lake/pull/21
- [ ] Make sure no duplicate rows are added on collection - https://github.com/merico-dev/lake/pull/39
- [ ] MR collection - https://github.com/merico-dev/lake/pull/60 https://github.com/merico-dev/lake/pull/73
- [ ] Projects collection - https://github.com/merico-dev/lake/pull/62
- [ ] Merge ratio - https://github.com/merico-dev/lake/pull/101
- [ ] Collect Data to support the following metrics:

Metric Name | Description
:------------ | :-------------
Pull Request Count | Number of Pull/Merge Requests
Pull Request Pass Rate | Ratio of Pull/Merge Review requests to merged
Pull Request Reviewer Count | Number of Pull/Merge Reviewers
Pull Request Review Time | Time from the first Pull/Merge Review comment until merged
Commit Author Count | Number of Contributors
Commit Count | Number of Commits
Added Lines | Accumulated Number of New Lines
Deleted Lines | Accumulated Number of Removed Lines

## Grafana

- [ ] Import all dashboards

## Devops

- [ ] grafana waits for other services - https://github.com/merico-dev/lake/pull/65 https://github.com/merico-dev/lake/pull/78
- [ ] Auto run migrations on docker-compose
- [ ] docker-compose prod mode
- [ ] Automatic collection loop

## Util

- [ ] fetch things from apis paginated - https://github.com/merico-dev/lake/pull/36 https://github.com/merico-dev/lake/pull/76
 https://github.com/merico-dev/lake/pull/96
## Readmes

- [ ] Update ts-main with all our good readmes from the main branch

**Comment by hezyin** [comment]
Done
