### ISSUE TITLE
CLI v2 Roadmap

### ISSUE THREAD

**Issue by joncodo** [merico-dev/lake#241]
## Description
These are the things we would like to see in the CLI

## Potential features fo terminal CLI
- [ ] validation on inputs (call test api, length, type of input)
- [ ] Use oauth to manage tokens
- [ ] Allow users to enable certain plugins and disable others
- [ ] Advanced cli for advanced configs (status types)
- [ ] Each plugin dictates what prompts for the cli to read
- [ ] The cli looks for all configs within each plugin
- [ ] Use the tokens to get all jira boards that the user has

### Application web interface
- [ ] Set up a local website to manage configs

### Code generator cli
- [ ] plugin bootstrapping with https://github.com/jondot/hygen
- [ ] modify plugins and add features
- [ ] migrations
