### ISSUE TITLE
Dev Lake Iteration (9/17-9/30) Plan

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#413]
## Timespan

9/17/21 - 9/30 (2 weeks)

## features / tasks

- [x] Gitlab CI https://github.com/merico-dev/lake/issues/405 @joncodo 
- [ ] Github https://github.com/merico-dev/lake/issues/407 @joncodo   @klesh @kevin-kline 
- [ ] Build the domain layer schema  **(issue link here)** @klesh 
- [ ] Jira to domain layer @klesh
- [ ] Gitlab to domain layer @joncodo 
- [ ] Jenkins to domain layer @narrowizard 
- [ ] Github to domain layer @joncodo @klesh 
- [x] Datasource specific dashboards - https://github.com/merico-dev/lake/issues/408 @joncodo 
- [ ] Jira mapping configuration https://github.com/merico-dev/lake/issues/399 @oddscenes @Startrekzky 
- [ ] config-ui landing guide (low priority) @oddscenes @Startrekzky 
- [ ] CI auto-build docker image / trigger mechanism **issue link here** @narrowizard ?

**Comment by klesh** [comment]
This issue should be replaced by a set of issues labelled with `iter1` and  grouped into Project Sep-Oct 2021.

**Comment by klesh** [comment]
All issues were created and link to Github Project, except `config-ui landing guide (low priority)` due to its priority.
