### ISSUE TITLE
Domain Layer Schema - V1.0

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#700]
## Description
In order to implement push API, we should determine the Domain Layer Schema, so that users can push their data to the domain layer directly.

![domain_layer_model_220110](https://user-images.githubusercontent.com/14050754/148776502-c06d2672-5115-4572-b33e-41f3ad0a4e90.png)

The detailed description of domain layer schema and the original model file can be found here: [Domain Layer Schema Document](https://merico.feishu.cn/docs/doccnvyuG9YpVc6lvmWkmmbZtUc#vWgNFS). 

## Todo
Data plugins and converters should be updated based on this. https://github.com/merico-dev/lake/issues/690 is a subset of this issue.

Action items

- [x] table.issues should support `type`, `status`, `priority` #690 
- [x] table.issues should include `lead_time_minutes`  #736
- [x] #909
- [ ] #490 add `issue_commits` entity to domain layer 
- [x] #910
- [ ] #915
- [x] #911
- [x] #912 
- [ ] #914 
- [x] #913

For later
1. convert Jira `board_repo` entity to domain layer

## Notice
1. All `origin_key` in issue domain layer entities should include 'source_id' info @klesh 
2. How to convert Github issues to board_issues, boards, and board_repo these 3 missing entities?
   - to table board_issues: `issue_origin_key` is the origin_key of all collected issues, `board_origin_key` is transformed from all collected issues' repo_id
   - to table boards: `origin_key` is transformed from repo_id, `name` is the repo_name, `url` is the url of the repo's issue list page
   - to table board_repo: `board_origin_key` is transformed from all collected issues' repo_id, `repo_origin_key` is transformed from all collected issues' repo_id too. 
3. We can ignore the CI domain for now as the data is not used in demo dashboards

**Comment by joncodo** [comment]
## Assumptions
I assume that you want to convert as many of the graphs in grafana to the domain layer as possible. 

## Questions:
1. Right now, we have a lot of dashboards in grafana. Do we care about all of them or are we only maintaining the demo dashboards?
2. Are there any charts that we want to support that are not written with domain layer queries?
3. What is there left for me to do on this task?

**Comment by Startrekzky** [comment]
> ## Assumptions
> I assume that you want to convert as many of the graphs in grafana to the domain layer as possible.
> 
> ## Questions:
> 1. Right now, we have a lot of dashboards in grafana. Do we care about all of them or are we only maintaining the demo dashboards?
> 2. Are there any charts that we want to support that are not written with domain layer queries?
> 3. What is there left for me to do on this task?

1. we only care about demo dashboards for now
2. yes, my plan is to do it next month
3. when the domain layer schema is updated, all entities enrichment logic should align with the new design. I'll adjust the subtasks in this issue to make them independently deliverable.

**Comment by Startrekzky** [comment]
Updated to https://merico.feishu.cn/docs/doccnvyuG9YpVc6lvmWkmmbZtUc#

**Comment by Startrekzky** [comment]
Updated at 21-01-10. [See doc](https://merico.feishu.cn/docs/doccnvyuG9YpVc6lvmWkmmbZtUc#)
Closed it for now. All future modification of domain layer schema will be recorded in #1051
