### ISSUE TITLE
Documentation for all iter 4 work

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#725]
## Documentation Scope
- [x] https://github.com/merico-dev/lake/issues/777
- [x] https://github.com/merico-dev/lake/issues/779
- [x] https://github.com/merico-dev/lake/issues/778
- [x] https://github.com/merico-dev/lake/issues/781
- [x] https://github.com/merico-dev/lake/issues/782
- [x] https://github.com/merico-dev/lake/issues/754
- [x] https://github.com/merico-dev/lake/issues/784
- [x] #750 
- [x] https://github.com/merico-dev/lake/issues/780

**Comment by klesh** [comment]
solved
