### ISSUE TITLE
QA three setup workflows for demo day

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#757]
## Description
Simulate a brand new user to finish following these setup workflows.

### First Round

- [x] Dev Setup @mindlesscloud 
- [x] User Setup via docker-compose (high) @klesh 
- [x] TeamCode setup (high) @Startrekzky 

### Second Round

- [x] Dev Setup as described in readme @kevin-kline 
- [x] User Setup as described in readme @kevin-kline 
- [x] Click [here](https://www.teamcode.com/tin/clone?applicationId=259777118600769536) to try TeamCode Setup with [Chinese Guide](https://github.com/merico-dev/lake/wiki/How-to-Set-Up-Dev-Lake-with-Tin-zh-CN) @mindlesscloud 
- [x] Click [ here](https://www.teamcode.com/tin/clone?applicationId=259777118600769536) to try TeamCode Setup with [English Guide](https://github.com/merico-dev/lake/wiki/How-to-Set-Up-Dev-Lake-with-Tin) @kevin-kline 

## Related issues:
- [x] #745 refers to https://github.com/merico-dev/lake/wiki/Set-Up-Dev-Lake-with-Tin-zh-CN

**Comment by kevin-kline** [comment]
From my testing both User Setup and Dev Setup work to get the project up and running without error. 
- Collections can be triggered
- Config UI saves to .env / DB

**Comment by kevin-kline** [comment]
In reference to the Tin setup: https://github.com/merico-dev/lake/wiki/Setting-Up-Dev-Lake-with-Tin

I can confirm this setup works well up to the collection stage:

![image](https://user-images.githubusercontent.com/27032263/142048721-24084346-fbbf-4a9e-9e5a-9b810f9d0ad5.png)

It is difficult to test because I don't have access to the DB or the backend logs to make sure that collection is happening. It takes time to collect the data. I'm still waiting. I'll follow up when it finishes (hopefully!)

**Comment by kevin-kline** [comment]
> In reference to the Tin setup: https://github.com/merico-dev/lake/wiki/Setting-Up-Dev-Lake-with-Tin
> 
> I can confirm this setup works well up to the collection stage:
> 
> ![image](https://user-images.githubusercontent.com/27032263/142048721-24084346-fbbf-4a9e-9e5a-9b810f9d0ad5.png)
> 
> It is difficult to test because I don't have access to the DB or the backend logs to make sure that collection is happening. Unfortunately we don't have the best updates on progress. I'm also not sure if the frontend would report any error if we have invalid tokens and have errors in the requests. However, it does takes time to collect the data. I'm still waiting. I'll follow up when it finishes (hopefully!)

Never finished. I found the backend logs, and I see an error happening:

![image](https://user-images.githubusercontent.com/27032263/142053717-765bd2f0-d83f-466d-9e33-603201152690.png)

**Comment by kevin-kline** [comment]
Here is an error after running Jira for about 20 minutes:

![image](https://user-images.githubusercontent.com/27032263/142060591-f477b225-4426-4722-a6c6-9be7811d6107.png)

**Comment by kevin-kline** [comment]
It also seems like my connection settings get lost, maybe after a certain timeout:

![image](https://user-images.githubusercontent.com/27032263/142061730-5bd7618a-5e11-423c-a8a1-4a305c9ec17a.png)

**Comment by kevin-kline** [comment]
Maybe this explains my problem. I seem to have run out of free time:

![image](https://user-images.githubusercontent.com/27032263/142062198-1f0f5c5c-a4f6-4d73-96b0-eb6a93f96c6d.png)

**Comment by Startrekzky** [comment]
> > In reference to the Tin setup: https://github.com/merico-dev/lake/wiki/How-to-set-Up-Dev-Lake-with-Tin
> > I can confirm this setup works well up to the collection stage:
> > ![image](https://user-images.githubusercontent.com/27032263/142048721-24084346-fbbf-4a9e-9e5a-9b810f9d0ad5.png)
> > It is difficult to test because I don't have access to the DB or the backend logs to make sure that collection is happening. Unfortunately we don't have the best updates on progress. I'm also not sure if the frontend would report any error if we have invalid tokens and have errors in the requests. However, it does takes time to collect the data. I'm still waiting. I'll follow up when it finishes (hopefully!)
> 
> Never finished. I found the backend logs, and I see an error happening:
> 
> ![image](https://user-images.githubusercontent.com/27032263/142053717-765bd2f0-d83f-466d-9e33-603201152690.png)

@mindlesscloud can not reproduce this error, so we decide to close this issue for now.
