### ISSUE TITLE
Revamp the Github plugin readme

### ISSUE THREAD

**Issue by hezyin** [merico-dev/lake#777]
## Description

Right now the Github plugin readme is incomplete. We need to add the necessary information. Please use the structure proposed in https://github.com/merico-dev/lake/issues/778 as a reference

Some specific todo items (note this is not a complete list):

- [x] how to get authentication token
- [x] introduce Github rate limit and how to use multiple authentication tokens to speed data collection up
- [x] add a link to the GitHub readme in the main readme
- [x] add a screenshot of Grafana dashboard
- [x] etc

## Division of Labor

- @e2corporation will take care of the "Configuration" section
- @kevin-kline will take care of the rest
