### ISSUE TITLE
All plugin readmes should share a similar structure

### ISSUE THREAD

**Issue by hezyin** [merico-dev/lake#778]
## Description

Our plugin readmes should conform to a general structure for consistency and best user experience.

## Proposed Readme Structure

1. Summary: a quick intro for what this plugin is about, would be nice to also have a screenshot from Grafana
2. Data & Metrics: a summary of what data we collect from the datasource, and what metrics we compute out of them, ideally both in table format
3.  Configuration
    3a. Datasource connection: mostly concerned with datasource endpoint and authentication
    3b. Datasource configuration: this is where we explain configurations like Jira's type mappings. Please make sure the order of subsections align with config UI's order for best user experience.
4. [Optional] Plugin API: the APis that this plugin provides

## Division of Labor

- [x] Incorporate config section written by Julien to Github plugin readme @e2corporation
- [x] Incorporate config section written by Julien to Gitlab plugin readme @e2corporation 
- [x] Incorporate config section written by Julien to Jira plugin readme @kevin-kline **** I am leaving Klesh's version****
- [x] Incorporate config section written by Julien to Jenkins plugin readme @kevin-kline

**Comment by e2corporation** [comment]
## 3. GitHub Configuration
### 3a. Provider (Datasource) Connection
The connection aspect of the configuration screen requires the following key fields to connect to the **GitHub API**. As GitHub is a _single-source data provider_ at the moment, the connection name is read-only as there is only one instance to manage. As we continue our development roadmap we may enable _multi-source_ connections for GitHub in the future.

- **Connection Name** [`READONLY`]
  - ⚠️ Defaults to "**Github**" and may not be changed.
- **Endpoint URL** (REST URL, starts with `https://` or `http://`)
  - This should be a valid REST API Endpoint eg. `https://api.github.com/`
- **Auth Token(s)** (Personal Access Token)
  - Provide at least one token for Authentication with the . This field accepts a comma-separated list of values for multiple tokens. The data collection will take longer for GitHub since they have a **rate limit of 2k requests per hour**. ::You can accelerate the process by configuring _multiple_ personal access tokens.::

For help on **Creating a personal access token**, please see official [GitHub Docs on Personal Tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)
    
For an overview of the **GitHub REST API**, please see official [GitHub Docs on REST](https://docs.github.com/en/rest)
    
Click **Save Connection** to update connection settings.
    

### 3b. Provider (Datasource) Settings
Manage additional settings and options for the GitHub Datasource Provider. Currently there is only one **optional** setting, *Proxy URL*. If you are behind a corporate firewall or VPN you may need to utilize a proxy server.

**GitHub Proxy URL [ `Optional`]**
Enter a valid proxy server address on your Network, e.g. `http://your-proxy-server.com:1080`

Click **Save Settings** to update additional settings.

**Comment by e2corporation** [comment]
## 3. JIRA Configuration
### 3a. Provider (Datasource) Connection
The connection aspect of the configuration screen requires the following key fields to connect to the **JIRA API**. JIRA is a _multi-source_ data provider and you may create multiple connection instances. When triggering collection, remember to specify  the **Connection Source ID** in the JSON Options payload for the instance you wish to run.

- **Connection Name** [`READONLY`]
  - Enter a user-friendly name for this connection source, e.g **your-team.atlassian.net**. Instance names are *Unique* and you may not use the same name more than once.
- **Endpoint URL** (REST URL, starts with `https://` or `http://`)
  - This should be a valid REST API Endpoint eg.Enter Endpoint URL eg.  `https://your-domain.atlassian.net/rest/api`
- **Basic Auth Token** (Base64 Encoded)
  - Enter the Basic Token for accessing this JIRA Instance. You may generate this token by using the command line to base64 encode the string `email:token` format, or use the supplied **Token Creator** in the UI to create one on the fly by providing E-mail and Password (or Token).
```
# Generate Basic 64 Token from CLI
$> echo -n <jira login email>:<jira token> | base64
```
For help on **Creating a Basic auth token**, please see official [JIRA Docs for REST APIs](https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/)
    
Click **Save Connection** to update connection settings.

### 3b. Provider (Datasource) Settings
Manage additional settings and options for the JIRA Datasource Provider. Our JIRA integration offers flexible settings to further refine the collection process.

**Issue Type Mappings [ `Optional`]**
Map your own issue types to Dev Lake's standard types. If you choose not to customize the mapping types, the **Standard Mapping Type** rules will take effect. 
- **`REQUIREMENT`**
- **`BUG`**
- **`INCIDENT`** 

You can associate more than one issue type to the top-level types mentioned before. For example **Bug** can map to **Bug-1** and **Bug-2**, (`Bug:Bug-1,Bug-2`).

Simply use the multi-tag input selector to add tags. Remember to click **ENTER** to save a tag once typed. You may change these selections at any time by modifying the **Settings** for this instance.

**Epic Key**
Choose the JIRA field you’re using to represent the key of an Epic to which an issue belongs to.

**Story Point Field [ `Optional`]**
Choose the JIRA field you’re using to represent the granularity of a requirement-type issue. 
 - **This defaults to 1 if not provided or empty.**

**Story Point Coefficient [ `Optional`]**
This is a number that can convert your JIRA story points to a new magnitude.  IE: Convert days to hours with 8 since there are 8 working hours in a day.


Click **Save Settings** to update additional settings.

**Comment by e2corporation** [comment]
## 3. GitLab Configuration
### 3a. Provider (Datasource) Connection
The connection aspect of the configuration screen requires the following key fields to connect to the **GitLab API**. As GitLab is a _single-source data provider_ at the moment, the connection name is read-only as there is only one instance to manage. As we continue our development roadmap we may enable _multi-source_ connections for GitLab in the future.

- **Connection Name** [`READONLY`]
  - ⚠️ Defaults to "**Gitlab**" and may not be changed.
- **Endpoint URL** (REST URL, starts with `https://` or `http://`)
  - This should be a valid REST API Endpoint eg. `https://gitlab.example.com/api/v4/`
- **Personal Access Token** (HTTP Basic Auth)
  - Login to your Gitlab Account and create a **Personal Access Token** to authenticate with the API using HTTP Basic Authentication.. The token must be 20 characters long. Save the personal access token somewhere safe. After you leave the page, you no longer have access to the token.

    1. In the top-right corner, select your **avatar**.
    2. Select **Edit profile**.
    3. On the left sidebar, select **Access Tokens**.
    4. Enter a **name** and optional **expiry date** for the token.
    5. Select the desired **scopes**.
    6. Select **Create personal access token**.

For help on **Creating a personal access token**, please see official [GitLab Docs on Personal Tokens](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html)
    
For an overview of the **GitLab REST API**, please see official [GitLab Docs on REST](https://docs.gitlab.com/ee/development/documentation/restful_api_styleguide.html#restful-api)
    
Click **Save Connection** to update connection settings.
    
### 3b. Provider (Datasource) Settings
Manage additional settings and options for the GitLab Datasource Provider. Currently there is only one **optional** setting that allows you to Map multiple JIRA Boards to GitLab Projects.

**JIRA Board Mappings [ `Optional`]**
**Map JIRA Boards to GitLab**. Type comma separated mappings using the format `[JIRA_BOARD_ID]:[GITLAB_PROJECT_ID]`
```
# Map JIRA Board ID 8 ==> Gitlab Projects 8967944,8967945
<JIRA_BOARD>:<GITLAB_PROJECT_ID>,...; eg. 8:8967944,8967945;9:8967946,8967947
```
Click **Save Settings** to update additional settings.

**Comment by e2corporation** [comment]
## 3. Jenkins Configuration
### 3a. Provider (Datasource) Connection
The connection aspect of the configuration screen requires the following key fields to connect to the **Jenkins API**. As Jenkins is a _single-source data provider_ at the moment, the connection name is read-only as there is only one instance to manage. As we continue our development roadmap we may enable _multi-source_ connections for Jenkins in the future.

- **Connection Name** [`READONLY`]
  - ⚠️ Defaults to "**Jenkins**" and may not be changed.
- **Endpoint URL** (REST URL, starts with `https://` or `http://`)
  - This should be a valid REST API Endpoint eg. `https://ci.jenkins.io/api`
- **Username** (E-mail)
  - Your User ID for the Jenkins Instance.
- **Password** (Secret Phrase)
  - Secret password for common credentials.

For help on **Username and Password**, please see official [Jenkins Docs on Using Credentials](https://www.jenkins.io/doc/book/using/using-credentials/)
    
For an overview of the **Jenkins REST API**, please see official [Jenkins Docs on Remote Access API](https://www.jenkins.io/doc/book/using/remote-access-api/)
    
Click **Save Connection** to update connection settings.
    
### 3b. Provider (Datasource) Settings
This integration doesn’t require any configuration. You can continue to _add other data sources_  or trigger collection at the previous page.

NOTE: The **Save Settings** button will be disabled until options are added for Jenkins.

**Comment by kevin-kline** [comment]
@Startrekzky @hezyin I am leaving @klesh 's version in for Jira. Julien's is also good, but I don't think it adds any new info to what Klesh already has there.
