### ISSUE TITLE
Final proofread of docs

### ISSUE THREAD

**Issue by hezyin** [merico-dev/lake#780]
## Documentation Scope

Final proofread of the following docs, looking for outdated and missing information:

- [x] main readme English review. required by @Startrekzky
- [x]  main readme Chinese @Startrekzky
- [x] wikis. review required by @Startrekzky 
- [x] Github readme. updated by @mindlesscloud, review required by @e2corporation
- [x] Jira readme.  updated by @klesh, review required by @e2corporation
- [x] Gitlab readme.  updated by @mindlesscloud, review required by @kevin-kline 
- [x] Jenkins readme @klesh has updated,  review required by @kevin-kline

**Comment by klesh** [comment]
solved
