### ISSUE TITLE
`pipeline blueprint` feature for recurring execution

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#877]
## Description
According to proposal from @joncodo during previous disccussion. We are going to add a `plan` entity on top of `pipeline`

## Describe the solution you'd like

1. `plan`: component that only stores the task topology and collection options, and a optional timer for automation.
2. `pipeline`:  component that represents a specific run of a plan, stores the start time, end time, status, and other info related to a run

The UI mockup are still pretty much the same as https://github.com/merico-dev/lake/issues/824#issuecomment-978570770
Only thing changed was terms/names, because:
1. To align our terminology to `gitlab` which `pipeline` is a history record of a RUN
2. This idea came out in the middle of my implementation of `pipeline`, change the meaning of `pipeline` would cause massive code refactor, we could still do that if most of us believed that is the right thing to do.

### Plan of attack:

- [x] `pipeline api` #864 
- [ ] Initial Triggers Design revamp started with #843
- [x] config-ui Triggers adopt `pipeline-api` #864 
- [x] config-ui Pipeline page feature, to replace Tasks, user enters name/tasks, then submit and run; user can re-run a specific pipeline, which essential create a new one based on existing  pipeline information #835 
- [x] `plan api`
- [x] `config-ui` Plan page feature, adopt `plan api` so user can create a Recurring Pipeline, it can be trigger by timer or manually

In general, `pipeline` is a **one off** execution, itself can operate independantly; `plan` is **recurring**, build on top of  `pipeline`, clients like EE or normal User can decide which one they like to adopt based on their needs.

## Has the Feature been Requested Before?
No

@hezyin @joncodo @kevin-kline @e2corporation @liangjingyang @mindlesscloud @Startrekzky

**Comment by kevin-kline** [comment]
> 

I think the naming of ```plan``` and ```pipeline``` sound inaccurate. To me, plan is too generic and could be easily confused with other meanings of the word (such as payment plan).

To me, the description of ```plan``` sounds like a ```pipeline``` or ```pipeline_blueprint```. The description of ```pipeline``` sounds like ```pipeline_run```.

I propose we rename ```plan``` to ```pipeline``` and ```pipeline``` to ```pipeline_run```.

Agree/Disagree? @joncodo @klesh @Startrekzky @hezyin

**Comment by Startrekzky** [comment]
> > 
> 
> I think the naming of `plan` and `pipeline` sound inaccurate. To me, plan is too generic and could be easily confused with other meanings of the word (such as payment plan).
> 
> To me, the description of `plan` sounds like a `pipeline` or `pipeline_blueprint`. The description of `pipeline` sounds like `pipeline_run`.
> 
> I propose we rename:
> 
> `plan` => `pipeline` or `pipeline_blueprint` `pipeline` => `pipeline_run`.
> 
> Agree/Disagree? @joncodo @klesh @Startrekzky @hezyin

I agree.

**Comment by warren830** [comment]
Plan of Attack：
1. new model pipeline_blueprint: 
type pipeline_blueprint struct {
name: 
pipeline_id: which pipeline run this blueprint 
cron_time: cron job format, like '5 * * * 2'
tasks: the same as pipeline
}
2. new api: define timer, part of create pipeline api 
blueprint {
day: { user can define monthDay or weekDay, if not define, cron job will work everyday
monthDay:  n
weekDay: n
intervalDay: /n run once every n days
}
hour:
minite:
}
3. realize in backend
