### ISSUE TITLE
All tasks including conversion tasks support canceling

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#920]
## Description
Right now only those collection tasks support canceling through `work_scheduler`, so when pipeline ran into these kind of tasks would cause the canceling command got ignored and end up with status `TASK_COMPLETED`

## Describe the solution you'd like
All tasks should support canceling with the same approach of https://github.com/merico-dev/lake/pull/956

1. Each `collector` either implementing `canceling` feature by adopting `SetContext` method from `ApiClient` or handling `ctx.Context`  correctly
2. Each `converter` should accept and handle `ctx.Context` correctly, like checking `ctx.Done()` inside each loop

- [x] all tasks from github plugin supports canceling
- [x] all tasks from gitlab plugin supports canceling
- [x] all tasks from jenkins plugin supports canceling
- [x] all tasks from jira plugin supports canceling

## Has the Feature been Requested Before?
No

## Additional context
Related to task #906 #996
