### ISSUE TITLE
PingCAP project

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/lake#949]
## Goal
To meet the analysis needs of PingCAP projects.

## User Story
P0 (Stage 1): 
1. As a project manager, I want to see how much work has been done in a specific release. (By calculating the Eloc of new commits on each release branch)
2. As a project manager, I want to see how much work (Eloc) has been done by each developer(/team/project) contribution in a specific release.
3. As a project manager, I want to see how much work (Eloc) has been spent and its percentage distribution on specific types of work (bug-fixing, incident-fixing, feature-dev, etc) across releases.
4. As a QA manager, I want to see how many bugs have been found during tests before a specific release. (**TBD**: how can we tell the bugs from incidents? How can we tell if a bug is found in a specific release?)
5. As a QA manager, I want to see the severity level distribution of bugs found during tests before a specific release. (**TBD**: Where to find severity level, is it a tag of a bug-type issue?)
6. As a QA manager, I want to see the bug distribution in high-level components (from issue tags) in a specific release.
7. As a QA manager, I want to see how many bugs have been found and fixed during tests before a specific release.
8. As a QA manager, I want to see how many incidents(bugs that haven't been found during tests) before a specific release. (**TBD**: how can we tell if a bug belongs to an incident of a specific release?)

P1 (Stage 2):
1. As a tech lead, I want to see the bug distribution in low-level components (from code files), as a guide for the future framework evolution.

P2 (Stage 3):
1. As a QA manager, I want to see what releases are affected by a bug-fixing commit, so that they can tag them and the bot can automatically fix those releases by cherrypicking.
2. As a QA manager, I want to check if the above cherrypicking is successful.
3. As a QA manager, I want to see the percentage of bugs found internally or externally.

**Comment by liangjingyang** [comment]
## TODO
- [ ] 1. Parse the PR id in the commit title and store the association in the domain layer.
- [ ] 2. Resolve the required attributes from the labels, such as bug/feature, component, and store them in the domain layer.
- [ ] 3. Extract the branch and tag of commits from git repository and store in domain layer.
- [ ] 4. Extract file-level data from git repository.
- [ ] 5. Fetch file-level dev equivalent from Analysis Engine.

**Comment by klesh** [comment]
- [ ] #1004 
- [ ] #1068
