### ISSUE TITLE
Refactor all plugins to `store raw response on collection and extract on enrichment` approach

### ISSUE THREAD

**Issue by klesh** [merico-dev/lake#983]
## Description
In order to solve usability issues like #575 , it makes sense to seperate collection/extraction into 2 step, and it also beneficial for plugin developer, since they can also reuse the collected raw data intead of collect from server whenever extraction logic was modified.

## Describe the solution you'd like
1. Separate collection/extraction into 2 tasks, just like https://github.com/merico-dev/lake/pull/967 did.
2. Whenever user modify any `customfield` setting from jira configuration of `config-ui`, prompt user to trigger Jira Issue Enrichment, create a pipeline if got confirmed.

- [ ] refactor all collection tasks from ae plugin to `store first extract later` approach
- [ ] refactor all collection tasks from github plugin to `store first extract later` approach
- [ ] refactor all collection tasks from githlab plugin to `store first extract later` approach
- [ ] refactor all collection tasks from jenkins plugin to `store first extract later` approach
- [ ] refactor all collection tasks from jira plugin to `store first extract later` approach
- [ ] `config-ui` prompt for re-enrich on `customfield` change and create a pipeline run accordingly if user confirmed

Related to https://github.com/merico-dev/lake/issues/575

**Comment by Startrekzky** [comment]
![image](https://user-images.githubusercontent.com/14050754/151557179-aeb25278-f72e-4e95-a989-7d9315dbe9ac.png)
